common: &COMMON
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails
  password: rails
  min_messages: warning

development:
  <<: *COMMON
  database: baseapp_development

test: &TEST
  <<: *COMMON
  database: baseapp_test

cucumber:
  <<: *TEST
